using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore; // ✅ Needed for Include()
using iTextSharp.text;
using iTextSharp.text.pdf;
using SparePartsWeb.Data;
using System.IO;
using System.Linq;

namespace SparePartsWeb.Controllers
{
    public class ReportsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;

        public ReportsController(AppDbContext context, IWebHostEnvironment env)
        {
            _context = context;
            _env = env;
        }

        public IActionResult Index()
        {
            // Include Vendor so it can be displayed
            var parts = _context.SpareParts.Include(p => p.Vendor).ToList();
            return View(parts);
        }

        public IActionResult GeneratePdf()
        {
            var parts = _context.SpareParts.Include(p => p.Vendor).ToList();

            using (MemoryStream ms = new MemoryStream())
            {
                // ✅ Create PDF document
                var doc = new Document(PageSize.A4, 36, 36, 54, 36);
                PdfWriter.GetInstance(doc, ms);
                doc.Open();

                // ✅ Add logo if available
                string logoPath = Path.Combine(_env.WebRootPath, "images", "logo.png");
                if (System.IO.File.Exists(logoPath))
                {
                    var logo = iTextSharp.text.Image.GetInstance(logoPath);
                    logo.ScaleToFit(100f, 100f);
                    logo.Alignment = Element.ALIGN_LEFT;
                    doc.Add(logo);
                }

                // ✅ Fonts
                var titleFont = FontFactory.GetFont("Helvetica", 18, Font.BOLD);
                var smallItalic = FontFactory.GetFont("Helvetica", 10, Font.ITALIC);
                var headerFont = FontFactory.GetFont("Helvetica", 12, Font.BOLD);
                var normalFont = FontFactory.GetFont("Helvetica", 11, Font.NORMAL);

                // ✅ Title
                var title = new Paragraph("Spare Parts Inventory Report", titleFont)
                {
                    Alignment = Element.ALIGN_CENTER,
                    SpacingAfter = 20
                };
                doc.Add(title);

                // ✅ Date
                var date = new Paragraph($"Generated on: {DateTime.Now:MMMM dd, yyyy HH:mm:ss}", smallItalic)
                {
                    Alignment = Element.ALIGN_RIGHT,
                    SpacingAfter = 20
                };
                doc.Add(date);

                // ✅ Table with Vendor column
                PdfPTable table = new PdfPTable(6)
                {
                    WidthPercentage = 100
                };
                table.SetWidths(new float[] { 7f, 20f, 18f, 20f, 15f, 20f });

                var lightGray = new BaseColor(230, 230, 230);
                string[] headers = { "ID", "Name", "Brand", "Vendor", "Quantity", "Price (Ksh)" };

                foreach (var header in headers)
                {
                    var cell = new PdfPCell(new Phrase(header, headerFont))
                    {
                        HorizontalAlignment = Element.ALIGN_CENTER,
                        BackgroundColor = lightGray,
                        Padding = 5
                    };
                    table.AddCell(cell);
                }

                // ✅ Rows
                foreach (var part in parts)
                {
                    table.AddCell(new Phrase(part.Id.ToString(), normalFont));
                    table.AddCell(new Phrase(part.Name, normalFont));
                    table.AddCell(new Phrase(part.Brand ?? "N/A", normalFont));
                    table.AddCell(new Phrase(part.Vendor?.Name ?? "—", normalFont));
                    table.AddCell(new Phrase(part.Quantity.ToString(), normalFont));
                    table.AddCell(new Phrase($"{part.Price:N2}", normalFont));
                }

                doc.Add(table);

                // ✅ Total stock value
                var totalValue = parts.Sum(p => p.Price * p.Quantity);
                var totalParagraph = new Paragraph($"\nTotal Inventory Value: Ksh {totalValue:N2}", headerFont)
                {
                    Alignment = Element.ALIGN_RIGHT,
                    SpacingBefore = 15
                };
                doc.Add(totalParagraph);

                // ✅ Footer
                var footer = new Paragraph($"\nReport generated by SparePartsWeb System © {DateTime.Now.Year}", smallItalic)
                {
                    Alignment = Element.ALIGN_CENTER,
                    SpacingBefore = 20
                };
                doc.Add(footer);

                doc.Close();

                return File(ms.ToArray(), "application/pdf", "SparePartsReport.pdf");
            }
        }
    }
}
